public class AuctionCampaignUtilsHelper {
/*
	public static String assignVenueGroup(Datetime startDate){
        String vg = null;

        if (startDate != null) {
            DateTime cutoff = DateTime.newInstance(2014, 3, 10, 0, 0, 0);
            Integer day = startDate.date().toStartOfWeek().daysBetween(startDate.date());
            Integer hour = startDate.hour();

            if (startDate <= cutoff) {
                vg = 'A';
            } else {
                if (day > 5 || day < 2 || (day == 5 && startDate.hour() >= 16) || (day == 2 && startDate.hour() < 16)) {
                    vg = 'A';
                } else {
                    vg = 'B';
                }
            }
        }

        return vg;
	}
*/
	//public void setVenueStateRegion(Auction_Campaign__c ac){
		
	//}	
}